dist: xenial
language: node_js
node_js:
  - "9"
  - "10"
services:
  - redis
  - mongodb
cache: npm
install:
    - "cd api && yarn"
script:
    - "yarn run test -- --grep worker"
after_success:
    - "yarn run coverage"
