version: '3.7'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        logging:
            driver: "json-file"
            options:
                max-size: "100MB"
                max-file: "3"
        environment:
            NODE_ENV: production
            DOCKER: 'true'
            PRODUCT_URL: https://getstream.io/winds
            PRODUCT_NAME: Winds
            PRODUCT_AUTHOR: Stream
            DATABASE_URI: mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD@production-z0pb8.mongodb.net/WINDS?retryWrites=true
            CACHE_URI: winds.x3kxi3.0001.use1.cache.amazonaws.com
            JWT_SECRET: bxRVJkuuMSvGw1dk8OQkFMxCVbxyOE
            API_PORT: 8080
            STREAM_API_BASE_URL: https://windspersonalization.getstream.io/personalization/v1.0
            STREAM_APP_ID: 12274
            STREAM_API_KEY: x8d94mnswb54
            STREAM_API_SECRET: btsuuncq93dsppnef3x8uwz76qdg7xuzcefn3jrfsqdknt4c5m9jqx5t2423aceecd
            ALGOLIA_WRITE_KEY: 2f67f0b715723442796eeb08be29f2bcd
            MERCURY_KEY: WNVuoBObRrvZRBG3SCsiAwN5dfdKIJ6x
